on:
  schedule:
    - cron: '24 19 * * *' 

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://www.faktury-online.com/api/init
          configuration: '{ "method": "GET", "headers": {"key": "${{ secrets.API_KEY }}", "email": "${{ secrets.EMAIL }}" } }'
